[workspace]
members = [
    "2016",
    "2018",
    "2019",
    "2020",
    "2021",
    "2022",
    "2022/2022_20",
    "2023",
    "aoclib",
]

[profile.dev]
opt-level = 1

[profile.release]
debug = true
lto = true
codegen-units = 1
