[package]
name = "aoc2018"
version = "0.1.0"
authors = ["Martin Pool <mbp@sourcefrog.net>"]
edition = "2021"

[dependencies]
itertools = "0.10"
lazy_static = "1"
regex = "1"
pest = "2.0"
pest_derive = "2.0"
