[package]
name = "aoc_2021"
version = "0.1.0"
edition = "2018"

[dependencies]
bitvec = "0.19"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.aoclib]
path = "../aoclib"
