[package]
name = "mbpaoc2022_20"
version = "0.0.0"
edition = "2021"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.10.5"

[dev-dependencies]
proptest = "1.0"
